/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FetchOptions {
  remote?: string
  prune?: boolean
  credentialsCallback?: (url: string, username?: string) => Credentials
  skipCertificateCheck?: boolean
}
export const enum ReferenceType {
  Direct = 1,
  Symbolic = 2
}
export const enum RepositoryState {
  Clean = 0,
  Merge = 1,
  Revert = 2,
  RevertSequence = 3,
  CherryPick = 4,
  CherryPickSequence = 5,
  Bisect = 6,
  Rebase = 7,
  RebaseInteractive = 8,
  RebaseMerge = 9,
  ApplyMailbox = 10,
  ApplyMailboxOrRebase = 11
}
export const enum ResetType {
  Soft = 0,
  Hard = 1,
  Mixed = 2
}
export class Commit {
  asObject(): object
  oid(): Oid
}
export class Credentials {
  static default(): Credentials
  static usernameAndPassword(username: string, password: string): Credentials
  static sshKeyFromMemory(username: string, publicKey: string | undefined | null, privateKey: string, passphrase?: string | undefined | null): Credentials
}
export class Oid { }
export class Object { }
export class Reference { }
export class Repository {
  static init(path: string, bare?: boolean | undefined | null): Promise<Repository>
  static open(path: string): Promise<Repository>
  static clone(url: string, path: string, recursive?: boolean | undefined | null, fetchOptions?: FetchOptions | undefined | null): Promise<Repository>
  namespace(): string | null
  isBare(): boolean
  isEmpty(): boolean
  path(): string
  state(): Promise<RepositoryState>
  findCommit(target: Oid): Commit
  createBranch(name: string, commit: Commit | Oid | string, force: boolean): Reference
  fetch(options?: FetchOptions | undefined | null): Promise<void>
  getCurrentBranch(): Reference
  head(): Reference
  reset(target: Commit | Reference | Oid, resetType?: ResetType | undefined | null): void
  getReference(reference: string): Reference
  getReferenceNames(referenceType?: ReferenceType | undefined | null): Array<string>
}
